"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FilaPedidos_1 = require("./FilaPedidos");
var Pedido_1 = require("./Pedido");
var TipoComida_1 = require("./TipoComida");
var comida1 = new Pedido_1.Pedido("arroz", TipoComida_1.TipoComida.areaSobremesa);
var comida2 = new Pedido_1.Pedido("bebida", TipoComida_1.TipoComida.bar);
var comida3 = new Pedido_1.Pedido("strogo", TipoComida_1.TipoComida.cozinha);
var comida4 = new Pedido_1.Pedido("comida", TipoComida_1.TipoComida.cozinha);
var comida5 = new Pedido_1.Pedido("doce", TipoComida_1.TipoComida.areaSobremesa);
var comida6 = new Pedido_1.Pedido("leite", TipoComida_1.TipoComida.bar);
var fila1 = new FilaPedidos_1.FilaPedidos();
fila1.adicionarPedido(comida1);
fila1.mostrarFila();
fila1.adicionarPedido(comida2);
fila1.mostrarFila();
fila1.adicionarPedido(comida3);
fila1.mostrarFila();
fila1.adicionarPedido(comida4);
fila1.mostrarFila();
fila1.adicionarPedido(comida5);
fila1.mostrarFila();
fila1.adicionarPedido(comida6);
fila1.mostrarFila();
