"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Monster_1 = require("./Monster");
var Warrior_1 = require("./Warrior");
var Moonstro = new Monster_1.Monster('Canine');
var Guerreiro = new Warrior_1.Warrior('Perseus', 'Brute', 5);
console.log("\nMonster Stats:\nName: ".concat(Moonstro.getName(), "\nHealth: ").concat(Moonstro.health, "\nForce: ").concat(Moonstro.force));
console.log("\nWarrior Stats:\nName: ".concat(Guerreiro.getName(), "\nType: ").concat(Guerreiro.getType(), "\nHealth: ").concat(Guerreiro.health, "\nForce: ").concat(Guerreiro.getForce(), "\n"));
Guerreiro.attackMonster(Moonstro);
Moonstro.lifeCheck();
Moonstro.getName();
Moonstro.setName('Catioro');
Moonstro.getName();
