"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ArrayList_1 = require("./Class/ArrayList");
var list = new ArrayList_1.ArrayList();
list.add(1);
list.add(2);
list.add(3);
list.add(4);
list.add(5);
console.log(list.addFirst(3));
console.log(list.addAt(2, "ola"));
console.log(list.remove(2));
console.log(list.removeFirst());
console.log(list.removeLast());
console.log(list.removeAt(4));
console.log(list.get(1));
console.log(list.indexOf("ola"));
console.log(list.isEmpty());
console.log(list.size());
