"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FilaDePedidos_1 = require("./Fila/FilaDePedidos");
var Pedidos_1 = require("./Classes/Pedidos");
var GerPedidos_1 = require("./Enum/GerPedidos");
var carneLoca = new Pedidos_1.Pedidos("carneLoca", GerPedidos_1.GerPedidos.Cozinha);
var strogonoff = new Pedidos_1.Pedidos("strogonoff", GerPedidos_1.GerPedidos.Cozinha);
var coca = new Pedidos_1.Pedidos("coca cola", GerPedidos_1.GerPedidos.Bar);
var fanta = new Pedidos_1.Pedidos("fanta", GerPedidos_1.GerPedidos.Bar);
var pudim = new Pedidos_1.Pedidos("pudim", GerPedidos_1.GerPedidos.Area_de_sobremesas);
var tortaDeBolacha = new Pedidos_1.Pedidos("torta de bolacha", GerPedidos_1.GerPedidos.Area_de_sobremesas);
var Fila = new FilaDePedidos_1.FilaDePedidos();
Fila.adicionarPedido(carneLoca);
Fila.olharLista();
Fila.adicionarPedido(coca);
Fila.olharLista();
Fila.adicionarPedido(fanta);
Fila.olharLista();
Fila.adicionarPedido(pudim);
Fila.olharLista();
Fila.adicionarPedido(strogonoff);
Fila.olharLista();
Fila.adicionarPedido(tortaDeBolacha);
Fila.olharLista();
Fila.quantidadePedidos();
